export const ItemDataSeed = [
  {
    itemName: 'Starbucks Guatemala Antigua',
    itemPrice: 16000,
    itemDetail: 'Elegant and refined with layers of lemon, chocolate and soft spice',
    type: 'coffee',
    imageUrl: 'https://www.starbucks.com',
    iso: 'GT',
    categoryId: 1,
    productCharacterId: null,
    coffeeCharacterId: 1,
  },
  {
    itemName: 'Fake Coffee',
    itemPrice: 10000,
    itemDetail: 'chinese fake coffee',
    type: 'coffee',
    imageUrl: 'https://www.idontlikeit.yes',
    iso: 'BR',
    categoryId: 1,
    productCharacterId: null,
    coffeeCharacterId: 2,
  },
  {
    itemName: 'yirgacheffe 101',
    itemPrice: 17900,
    itemDetail:
      'Ethiopian Yirgacheffe coffee is one of the most popular types of coffee in the world.',
    type: 'coffee',
    imageUrl: 'https://https://espressocoffeeguide.com',
    iso: 'ET',
    categoryId: 3,
    productCharacterId: null,
    coffeeCharacterId: 3,
  },
  {
    itemName: 'Kenyan coffee beans',
    itemPrice: 19900,
    itemDetail:
      'Kenyan coffee beans have distinctly bright taste with complex tones of fruit and berry.',
    type: 'coffee',
    imageUrl: 'https://www.idontlikeit.yes',
    iso: 'KE',
    categoryId: 1,
    productCharacterId: null,
    coffeeCharacterId: 4,
  },
  {
    itemName: 'Colombian coffee beans',
    itemPrice: 17000,
    itemDetail: 'medium-bodied with a rich taste and citrus-like acidity.',
    type: 'coffee',
    imageUrl: 'https://ravecoffee.co.uk/pages/colombian-coffee',
    iso: 'CO',
    categoryId: 1,
    productCharacterId: null,
    coffeeCharacterId: 5,
  },
  {
    itemName: 'French Press',
    itemPrice: 11000,
    itemDetail: 'special machine used to make coffee',
    type: 'product',
    imageUrl: 'https://www.thisisuseful.maybe.com',
    iso: null,
    categoryId: 2,
    productCharacterId: 1,
    coffeeCharacterId: null,
  },
  {
    itemName: 'Aeropress',
    itemPrice: 45000,
    itemDetail: 'You can brew coffee or espresso right over your mug!',
    type: 'product',
    imageUrl: 'https://www.idontknowwhatitis.net',
    iso: null,
    categoryId: 2,
    productCharacterId: 2,
    coffeeCharacterId: null,
  },
]
