export const ItemDataSeed = [
  {
    itemName: "Starbucks Coffee",
    itemPrice: 2000,
    itemDetail: "starbucky",
    type: "coffee",
    categoryId: 1,
    itemCharacterId: null,
    coffeeCharacterId: 1,
  },
  {
    itemName: "Fake Coffee",
    itemPrice: 1000,
    itemDetail: "chinese fake coffee",
    type: "coffee",
    categoryId: 1,
    itemCharacterId: null,
    coffeeCharacterId: 2,
  },
  {
    itemName: "French Press",
    itemPrice: 5000,
    itemDetail: "special machine used to make coffee",
    type: "machine",
    categoryId: 2,
    itemCharacterId: 1,
    coffeeCharacterId: null,
  },
  {
    itemName: "Aeropress",
    itemPrice: 10000,
    itemDetail: "You can brew coffee or espresso right over your mug!",
    type: "machine",
    categoryId: 2,
    itemCharacterId: 2,
    coffeeCharacterId: null,
  },
];
